package com.leika.shop.dto;

import lombok.Getter;
import lombok.Setter;

import java.util.List;
import java.util.Map;

@Getter
@Setter
public class ChatRequest {

    /** Current user message */
    private String message;

    /**
     * Browser-generated UUID that persists across page reloads.
     * Used to identify guests and link to UserBehavior / UserProfile.
     */
    private String sessionId;

    /**
     * Groups this message into a conversation window.
     * New conversation = new UUID generated by the frontend on first open.
     */
    private String conversationId;

    /**
     * Optional – legacy fallback history from localStorage.
     * When conversationId is present, server-side history takes precedence.
     * Each map: {"role": "user"/"assistant", "content": "..."}
     */
    private List<Map<String, String>> history;

    /** Product the user is currently viewing (for context injection) */
    private Integer currentProductId;

    /**
     * JSON-encoded style preferences from frontend (legacy – still accepted).
     * Server-side UserProfile takes precedence when available.
     */
    private String preferences;
}

